language: go
go:
  - stable
install:
  - cd ray-tracing
  - go mod download
before_script:
  - export CGO_ENABLED=0
script:
  - go test ./... -cover
after_success:
  - bash <(curl -s https://codecov.io/bash)
